### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by surevs** [mdmintz/SeleniumBase#43]
Hello, I have been very thankful for this framework to get started with automation aspects.
Its very pleasing to see many kinds of assertions being done on text and undoubtedly the best.
There is a package called 'needle' which does with Image checkpoint to include and noticed that it works very well with nosetests which actually make this framework even more robust.

https://pypi.python.org/pypi/needle
https://needle.readthedocs.io/en/latest/

**Comment by mdmintz** [comment]
Hi, Looks like it might be useful, but Needle's structure might make it better as a standalone tool or as an import for specific tests. Using NeedleTestCase as the parent class would be an issue in the current form because that would clash with using SeleniumBase's BaseCase as the parent class.
